# This is a TOML document. Boom.

# stream名称
name="console_stream"
# stream的流转方式
transitType=0
# 内存中缓存的数据数
cacheSize=100

[[pcfgs]]
workerName="testFile"
producer="file"
filePath="/home/huhaoran/z/text"
backDir="/home/huhaoran/z/"
position=1
rollType=1
delimiter="\n"
bufSize=0
filters=['point']

[[ccfgs]]
workerName="testFile"
consumer="console"
filters=['coma']
