# This is a TOML document. Boom.

# stream名称
name="console_stream"
# stream的流转方式
rollType=0
# 内存中缓存的数据数
cacheSize=100

[[pcfgs]]
producer="console"
delimiter="\n"
bufSize=0
filters=['point']

[[ccfgs]]
consumer="console"
filters=['coma']
